# Generated by Django 4.1.5 on 2023-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='body',
        ),
        migrations.AddField(
            model_name='clip',
            name='css',
            field=models.CharField(default='border:4mm ridge rgba(211, 220, 50, .6);', max_length=10000),
        ),
        migrations.AddField(
            model_name='clip',
            name='html',
            field=models.CharField(default='<div></div>', max_length=10000),
        ),
    ]
