# Generated by Django 4.1.5 on 2023-01-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_clip_body_clip_css_clip_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='css',
            field=models.TextField(default='border:4mm ridge rgba(211, 220, 50, .6);', max_length=10000),
        ),
        migrations.AlterField(
            model_name='clip',
            name='html',
            field=models.TextField(default='<div></div>', max_length=10000),
        ),
    ]
